/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'private_key_point_msg'
 * message type.
 */

public class private_key_point_msg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 66;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 12;

    /** Create a new private_key_point_msg of size 66. */
    public private_key_point_msg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new private_key_point_msg of the given data_length. */
    public private_key_point_msg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new private_key_point_msg with the given data_length
     * and base offset.
     */
    public private_key_point_msg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new private_key_point_msg using the given byte array
     * as backing store.
     */
    public private_key_point_msg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new private_key_point_msg using the given byte array
     * as backing store, with the given base offset.
     */
    public private_key_point_msg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new private_key_point_msg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public private_key_point_msg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new private_key_point_msg embedded in the given message
     * at the given base offset.
     */
    public private_key_point_msg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new private_key_point_msg embedded in the given message
     * at the given base offset and length.
     */
    public private_key_point_msg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <private_key_point_msg> \n";
      try {
        s += "  [len=0x"+Long.toHexString(get_len())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [coord=0x"+Long.toHexString(get_coord())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [c=";
        for (int i = 0; i < 64; i++) {
          s += "0x"+Long.toHexString(getElement_c(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: len
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'len' is signed (false).
     */
    public static boolean isSigned_len() {
        return false;
    }

    /**
     * Return whether the field 'len' is an array (false).
     */
    public static boolean isArray_len() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'len'
     */
    public static int offset_len() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'len'
     */
    public static int offsetBits_len() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'len'
     */
    public short get_len() {
        return (short)getUIntElement(offsetBits_len(), 8);
    }

    /**
     * Set the value of the field 'len'
     */
    public void set_len(short value) {
        setUIntElement(offsetBits_len(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'len'
     */
    public static int size_len() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'len'
     */
    public static int sizeBits_len() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: coord
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'coord' is signed (false).
     */
    public static boolean isSigned_coord() {
        return false;
    }

    /**
     * Return whether the field 'coord' is an array (false).
     */
    public static boolean isArray_coord() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'coord'
     */
    public static int offset_coord() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'coord'
     */
    public static int offsetBits_coord() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'coord'
     */
    public short get_coord() {
        return (short)getUIntElement(offsetBits_coord(), 8);
    }

    /**
     * Set the value of the field 'coord'
     */
    public void set_coord(short value) {
        setUIntElement(offsetBits_coord(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'coord'
     */
    public static int size_coord() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'coord'
     */
    public static int sizeBits_coord() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: c
    //   Field type: short[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'c' is signed (false).
     */
    public static boolean isSigned_c() {
        return false;
    }

    /**
     * Return whether the field 'c' is an array (true).
     */
    public static boolean isArray_c() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'c'
     */
    public static int offset_c(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 64) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'c'
     */
    public static int offsetBits_c(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 64) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'c' as a short[]
     */
    public short[] get_c() {
        short[] tmp = new short[64];
        for (int index0 = 0; index0 < numElements_c(0); index0++) {
            tmp[index0] = getElement_c(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'c' from the given short[]
     */
    public void set_c(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_c(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'c'
     */
    public short getElement_c(int index1) {
        return (short)getUIntElement(offsetBits_c(index1), 8);
    }

    /**
     * Set an element of the array 'c'
     */
    public void setElement_c(int index1, short value) {
        setUIntElement(offsetBits_c(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'c'
     */
    public static int totalSize_c() {
        return (512 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'c'
     */
    public static int totalSizeBits_c() {
        return 512;
    }

    /**
     * Return the size, in bytes, of each element of the array 'c'
     */
    public static int elementSize_c() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'c'
     */
    public static int elementSizeBits_c() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'c'
     */
    public static int numDimensions_c() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'c'
     */
    public static int numElements_c() {
        return 64;
    }

    /**
     * Return the number of elements in the array 'c'
     * for the given dimension.
     */
    public static int numElements_c(int dimension) {
      int array_dims[] = { 64,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'c' with a String
     */
    public void setString_c(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_c(i, (short)s.charAt(i));
         }
         setElement_c(i, (short)0); //null terminate
    }

    /**
     * Read the array 'c' as a String
     */
    public String getString_c() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,64)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_c(i) == (char)0) break;
             carr[i] = (char)getElement_c(i);
         }
         return new String(carr,0,i);
    }

}
