/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'shared_key_msg'
 * message type.
 */

public class shared_key_msg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 65;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 14;

    /** Create a new shared_key_msg of size 65. */
    public shared_key_msg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new shared_key_msg of the given data_length. */
    public shared_key_msg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new shared_key_msg with the given data_length
     * and base offset.
     */
    public shared_key_msg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new shared_key_msg using the given byte array
     * as backing store.
     */
    public shared_key_msg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new shared_key_msg using the given byte array
     * as backing store, with the given base offset.
     */
    public shared_key_msg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new shared_key_msg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public shared_key_msg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new shared_key_msg embedded in the given message
     * at the given base offset.
     */
    public shared_key_msg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new shared_key_msg embedded in the given message
     * at the given base offset and length.
     */
    public shared_key_msg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <shared_key_msg> \n";
      try {
        s += "  [sk_len=0x"+Long.toHexString(get_sk_len())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sk=";
        for (int i = 0; i < 64; i++) {
          s += "0x"+Long.toHexString(getElement_sk(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sk_len
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sk_len' is signed (false).
     */
    public static boolean isSigned_sk_len() {
        return false;
    }

    /**
     * Return whether the field 'sk_len' is an array (false).
     */
    public static boolean isArray_sk_len() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sk_len'
     */
    public static int offset_sk_len() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sk_len'
     */
    public static int offsetBits_sk_len() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'sk_len'
     */
    public short get_sk_len() {
        return (short)getUIntElement(offsetBits_sk_len(), 8);
    }

    /**
     * Set the value of the field 'sk_len'
     */
    public void set_sk_len(short value) {
        setUIntElement(offsetBits_sk_len(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'sk_len'
     */
    public static int size_sk_len() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sk_len'
     */
    public static int sizeBits_sk_len() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sk
    //   Field type: short[], unsigned
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sk' is signed (false).
     */
    public static boolean isSigned_sk() {
        return false;
    }

    /**
     * Return whether the field 'sk' is an array (true).
     */
    public static boolean isArray_sk() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'sk'
     */
    public static int offset_sk(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 64) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sk'
     */
    public static int offsetBits_sk(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 64) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'sk' as a short[]
     */
    public short[] get_sk() {
        short[] tmp = new short[64];
        for (int index0 = 0; index0 < numElements_sk(0); index0++) {
            tmp[index0] = getElement_sk(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'sk' from the given short[]
     */
    public void set_sk(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_sk(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'sk'
     */
    public short getElement_sk(int index1) {
        return (short)getUIntElement(offsetBits_sk(index1), 8);
    }

    /**
     * Set an element of the array 'sk'
     */
    public void setElement_sk(int index1, short value) {
        setUIntElement(offsetBits_sk(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'sk'
     */
    public static int totalSize_sk() {
        return (512 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'sk'
     */
    public static int totalSizeBits_sk() {
        return 512;
    }

    /**
     * Return the size, in bytes, of each element of the array 'sk'
     */
    public static int elementSize_sk() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'sk'
     */
    public static int elementSizeBits_sk() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'sk'
     */
    public static int numDimensions_sk() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'sk'
     */
    public static int numElements_sk() {
        return 64;
    }

    /**
     * Return the number of elements in the array 'sk'
     * for the given dimension.
     */
    public static int numElements_sk(int dimension) {
      int array_dims[] = { 64,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'sk' with a String
     */
    public void setString_sk(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_sk(i, (short)s.charAt(i));
         }
         setElement_sk(i, (short)0); //null terminate
    }

    /**
     * Read the array 'sk' as a String
     */
    public String getString_sk() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,64)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_sk(i) == (char)0) break;
             carr[i] = (char)getElement_sk(i);
         }
         return new String(carr,0,i);
    }

}
