/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'uint8_msg'
 * message type.
 */

public class uint8_msg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 102;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 16;

    /** Create a new uint8_msg of size 102. */
    public uint8_msg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new uint8_msg of the given data_length. */
    public uint8_msg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new uint8_msg with the given data_length
     * and base offset.
     */
    public uint8_msg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new uint8_msg using the given byte array
     * as backing store.
     */
    public uint8_msg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new uint8_msg using the given byte array
     * as backing store, with the given base offset.
     */
    public uint8_msg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new uint8_msg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public uint8_msg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new uint8_msg embedded in the given message
     * at the given base offset.
     */
    public uint8_msg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new uint8_msg embedded in the given message
     * at the given base offset and length.
     */
    public uint8_msg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <uint8_msg> \n";
      try {
        s += "  [len=0x"+Long.toHexString(get_len())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [content=";
        for (int i = 0; i < 101; i++) {
          s += "0x"+Long.toHexString(getElement_content(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: len
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'len' is signed (false).
     */
    public static boolean isSigned_len() {
        return false;
    }

    /**
     * Return whether the field 'len' is an array (false).
     */
    public static boolean isArray_len() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'len'
     */
    public static int offset_len() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'len'
     */
    public static int offsetBits_len() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'len'
     */
    public short get_len() {
        return (short)getUIntElement(offsetBits_len(), 8);
    }

    /**
     * Set the value of the field 'len'
     */
    public void set_len(short value) {
        setUIntElement(offsetBits_len(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'len'
     */
    public static int size_len() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'len'
     */
    public static int sizeBits_len() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: content
    //   Field type: short[], unsigned
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'content' is signed (false).
     */
    public static boolean isSigned_content() {
        return false;
    }

    /**
     * Return whether the field 'content' is an array (true).
     */
    public static boolean isArray_content() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'content'
     */
    public static int offset_content(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 101) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'content'
     */
    public static int offsetBits_content(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 101) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'content' as a short[]
     */
    public short[] get_content() {
        short[] tmp = new short[101];
        for (int index0 = 0; index0 < numElements_content(0); index0++) {
            tmp[index0] = getElement_content(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'content' from the given short[]
     */
    public void set_content(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_content(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'content'
     */
    public short getElement_content(int index1) {
        return (short)getUIntElement(offsetBits_content(index1), 8);
    }

    /**
     * Set an element of the array 'content'
     */
    public void setElement_content(int index1, short value) {
        setUIntElement(offsetBits_content(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'content'
     */
    public static int totalSize_content() {
        return (808 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'content'
     */
    public static int totalSizeBits_content() {
        return 808;
    }

    /**
     * Return the size, in bytes, of each element of the array 'content'
     */
    public static int elementSize_content() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'content'
     */
    public static int elementSizeBits_content() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'content'
     */
    public static int numDimensions_content() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'content'
     */
    public static int numElements_content() {
        return 101;
    }

    /**
     * Return the number of elements in the array 'content'
     * for the given dimension.
     */
    public static int numElements_content(int dimension) {
      int array_dims[] = { 101,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'content' with a String
     */
    public void setString_content(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_content(i, (short)s.charAt(i));
         }
         setElement_content(i, (short)0); //null terminate
    }

    /**
     * Read the array 'content' as a String
     */
    public String getString_content() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,101)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_content(i) == (char)0) break;
             carr[i] = (char)getElement_content(i);
         }
         return new String(carr,0,i);
    }

}
